import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import RingMenu from "../components/RingMenu";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

const porterSans = localFont({
  src: "./fonts/porter-sans-inline-block.otf",
  variable: "--font-porter-sans",
  weight: "100 900",
});
const porterMono = localFont({
  src: "./fonts/porter-sans-inline-block.ttf",
  variable: "--font-porter-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Alejandro?",
  description: "portfolio generated by Alejandro?",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${porterSans.variable} ${porterMono.variable} ${geistMono.variable} ${geistSans.variable} antialiased`}
      >
        <RingMenu /> {/* Floating Sidebar */}
        {children}
      </body>
    </html>
  );
}
